name: value_cubit
description: A dart package that helps implements basic states for BLoC library
repository: https://github.com/devobs/value_cubit
homepage: https://github.com/devobs
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  
  meta: ^1.7.0
  stream_transform: ^2.0.0
  synchronized: ^3.0.0
  
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
